### ISSUE TITLE
action is using an old version of the sdk

### ISSUE THREAD

**Issue by devoncarew** [yjbanov/flute#2]
The CI action for this repo is using an old version of the dart sdk (`2.15.0-268.18.beta`):

https://github.com/dart-lang/flute/blob/main/.github/workflows/ci.yaml#L21C34-L21C34

Is specifying an older sdk necessary here?

cc @askeksa @yjbanov

**Comment by devoncarew** [comment]
Likely related - the CI currently fails on `pub get`, and would hit issues after that w/ static analysis problems.

https://github.com/dart-lang/flute/actions/workflows/ci.yaml

**Comment by athomas** [comment]
Seems to have been fixed.
